name: delivery_pizza_api
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  args: ^1.6.0
  dotenv: ^2.0.0 #Para criar variáveis de ambiente. Posso criar um arquivo .env e 
                 #colocar elas lá dentro. Só indicado fazer isso para ambiente de desenvolvimento
  get_it: ^5.0.6 #Para injeção de dependencia.
  injectable: ^1.0.7 #Facilita a injeção de dependência com o get_it através de anotações
  mysql1: ^0.17.1 #Pacote para utilizar o mysql junto com o dart
  shelf: ^0.7.5 #Servidor RestFull em Dart
  shelf_router: ^0.7.4 #Facilita a criação de rotas no Shelf.

dev_dependencies:
  build_runner: ^1.11.0 #Cria os arquivos necessários para utilização de vários pacotes, inclusive o get_it
  injectable_generator: ^1.0.7 #Ajuda o injectable na criação dos arquivos de configuração.
  pedantic: ^1.9.0
  shelf_router_generator: ^0.7.2+4 #Ajuda o shelf nas criações das rotas.
